import { defineTextStyles } from "@chakra-ui/react";

export const textStyles = defineTextStyles({
  h1: {
    description: "H1 - Semi 28px",
    value: {
      fontFamily: "Roboto",
      fontWeight: "600",
      fontSize: "28px",
      lineHeight: "36",
      letterSpacing: "0",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  h2: {
    description: "H2 - Semi 24px",
    value: {
      fontFamily: "Roboto",
      fontWeight: "600",
      fontSize: "24px",
      lineHeight: "30",
      letterSpacing: "0",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  h3: {
    description: "H3 - Semi 22px",
    value: {
      fontFamily: "Roboto",
      fontWeight: "600",
      fontSize: "22px",
      lineHeight: "28",
      letterSpacing: "0",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  title1: {
    description: "Title 1 - Semi 18px",
    value: {
      fontFamily: "Roboto",
      fontWeight: "600",
      fontSize: "18px",
      lineHeight: "22",
      letterSpacing: "0",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  title2: {
    description: "Title 2  - Bold 16px",
    value: {
      fontFamily: "Roboto",
      fontWeight: "700",
      fontSize: "16px",
      lineHeight: "20",
      letterSpacing: "0",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  title3: {
    description: "Title 3  - Bold 14px",
    value: {
      fontFamily: "Roboto",
      fontWeight: "700",
      fontSize: "14px",
      lineHeight: "18",
      letterSpacing: "0",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  cotent1: {
    description: "Title 3  - Bold 14px",
    value: {
      fontFamily: "Roboto",
      fontWeight: "400",
      fontSize: "18px",
      lineHeight: "22",
      letterSpacing: "0",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  content2: {
    description: "Content 2 - Reg 16px",
    value: {
      fontFamily: "Roboto",
      fontWeight: "400",
      fontSize: "16px",
      lineHeight: "20",
      letterSpacing: "0",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  contentSemi2: {
    description: "Content 2 - Semi 16px",
    value: {
      fontFamily: "Roboto",
      fontWeight: "600",
      fontSize: "16px",
      lineHeight: "20",
      letterSpacing: "0",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  content3: {
    description: "Content 3 - Reg 14px",
    value: {
      fontFamily: "Roboto",
      fontWeight: "400",
      fontSize: "14px",
      lineHeight: "18",
      letterSpacing: "0",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  caption1: {
    description: "Caption 1 - Reg 12px",
    value: {
      fontFamily: "Roboto",
      fontWeight: "400",
      fontSize: "12px",
      lineHeight: "14.06",
      letterSpacing: "0",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  caption2: {
    description: "Caption 2 - Reg 10px",
    value: {
      fontFamily: "Roboto",
      fontWeight: "400",
      fontSize: "10px",
      lineHeight: "11.72",
      letterSpacing: "0",
      textDecoration: "None",
      textTransform: "None",
    },
  },
});
